---
title: "Project"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message = FALSE, warning = FALSE}
library(tidyverse) 
library(tidymodels)
``` 

```{r load-data, message = F}
food <- readr::read_csv("data/Food_Supply_kcal_Data.csv")
```

```{r coutnries}
food <- food %>%
  mutate(income = ifelse(Country %in% c("Afghanistan","Burkina Faso", "Central African Republic", "Chad", "Congo", "Ethiopia", "Gambia", "Guinea", "Guinea-Bissau", "Korea, Dem. People's Rep", "Liberia", "Madagascar", "Malawi", "Mali", "Mozambique", "Rwanda", "Sierra Leone", "Sudan", "Togo", "Uganda", "Yemen"),"LIC", 
                         ifelse(Country %in% c("Algeria","Angola","Bangladesh", "Belize", "Benin", "Bolivia", "Cabo Verde", "Cambodia", "Cameroon", "Cote d'Ivoire", "Djibouti", "Egypt", "El Salvador", "Eswatini", "Ghana", "Haiti", "Honduras", "India", "Indonesia", "Iran (Islamic Republic of)", "Kenya", "Kiribati", "Kyrgyzstan", "Lao People's Democratic Republic", "Lesotho", "Mauritania", "Mongolia", "Morocco", "Myanmar", "Nepal", "Nicaragua", "Niger", "Nigeria", "	
Pakistan", "Samoa", "Sao Tome and Principe", "Senegal", "Solomon Islands","Sri Lanka", "Suriname", "Tajikistan", "Timor-Leste", "Tunisia", "Ukraine", "United Republic of Tanzania", "Uzbekistan", "Vanuatu", "Vietnam", "Zambia", "Zimbabwe"), "LMIC", 
                         ifelse(Country %in% c("Albania","Argentina","Armenia","Azerbaijan", "Belarus","Bosnia and Herzegovina", "Botswana", "Brazil", "Bulgaria", "China", "Colombia", "Costa Rica", "Cuba", "Dominica", "Dominican Republic", "Ecuador", "Fiji", "Gabon", "Georgia", "Grenada", "Guatemala", "Guyana", "Iraq", "Jamaica", "Jordan", "Kazakhstan", "Lebanon", "Malaysia", "Maldives", "Mauritius", "Mexico", "Montenegro","Namibia", "North Macedonia", "	
Panama", "Paraguay", "Peru", "Philippines", "Republic of Moldova", "Romania", "Russian Federation", "Saint Lucia", "Saint Vincent and the Grenadines", "Serbia", "Senegal", "South Africa", "Thailand", "Turkey", "Turkmenistan", "Venezuela (Bolivarian Republic of)"),
             "UMIC", "HIC"))))
```

```{r}
food <- food %>% 
  mutate(Grains = `Cereals - Excluding Beer` + `Starchy Roots`) %>% 
  mutate(Vegetables2 = Pulses + `Vegetal Products` + Vegetables) %>% 
  mutate(Fruits = `Fruits - Excluding Wine`) %>% 
  mutate(Fats = `Animal fats` + Oilcrops + Treenuts + `Vegetable Oils`) %>% 
  mutate(Protein = `Animal Products` + Eggs + `Fish, Seafood` + Meat + `Milk - Excluding Butter` + Offals) %>% 
  mutate('Alcohol/Stimulants' = `Alcoholic Beverages` + Stimulants) %>% 
  mutate(Other = `Aquatic Products, Other` + Miscellaneous + Spices + `Sugar Crops` + `Sugar & Sweeteners`)
```

```{r}
meanfood <- food %>%
  summarize(meangrains = mean(Grains), meanveg = mean(Vegetables2), meanfruit = mean(Fruits), meanfat = mean(Fats), meanprotein = mean(Protein), meanother = mean(Other))

meanfoodincome <- food %>%
  group_by(income) %>%
  summarize(meangrains = mean(Grains), meanveg = mean(Vegetables2), meanfruit = mean(Fruits), meanfat = mean(Fats), meanprotein = mean(Protein), meanother = mean(Other)) %>% 
  add_row(income="USDA", meangrains=30, meanveg=40, meanfruit=10, meanprotein=20) %>% 
  pivot_longer(cols=meangrains:meanother, names_to = "Means", values_to = "PercentDiet") 

meanfoodincome %>%
  mutate(income = fct_relevel(income, 
            "HIC", "UMIC", "LMIC", 
            "LIC", "USDA")) %>%
  ggplot(aes(x=Means, y=PercentDiet, fill=income))+geom_col(position="dodge") + labs(x="Food Group", y="Percent of Total Diet Composition", title="Diet Make up by Food Group", subtitle="broken down by income category and compared to USDA suggested diet")
```

```{r}
tfood<-food %>%
  group_by(income) %>%
  summarize(meangrains = mean(Grains), meanveg = mean(Vegetables2), meanfruit = mean(Fruits), meanfat = mean(Fats), meanprotein = mean(Protein), meanother = mean(Other)) %>% 
  add_row(income="USDA", meangrains=30, meanveg=40, meanfruit=10, meanprotein=20)
```

```{r}
food <- food %>% 
   mutate(rec_rate=Recovered/Confirmed) 

res <- linear_reg() %>%
  set_engine("lm") %>%
  fit(rec_rate ~ income, data = food) %>%
  tidy() 
print(res)

food <- food %>% 
   mutate(death_rate=Deaths/Confirmed) 

res2 <- linear_reg() %>%
  set_engine("lm") %>%
  fit(death_rate ~ income, data = food) %>%
  tidy() 
print(res2)
```
```{r}
food <- food %>% 
  mutate(adherance_grains = (30 - Grains)^2) %>% 
  mutate(adherance_veg = (40 - Vegetables2)^2) %>% 
  mutate(adherance_fruit = (10 - Fruits)^2) %>% 
  mutate(adherance_protein = (20 - Protein)^2) %>% 
  mutate(adherance_tot = adherance_grains + adherance_protein + adherance_fruit + adherance_veg)
```

```{r}
reg <- linear_reg() %>%
  set_engine("lm") %>%
  fit(death_rate ~ adherance_tot + income, data = food) %>%
  tidy() 
print(reg)

```


